ifeq ($(subdir),misc)
sysdep_routines += \
  linx-libc-stubs \
  # sysdep_routines
endif

ifeq ($(subdir),elf)
sysdep-rtld-routines += \
  linx-rtld-stubs \
  linx-rtld-sync \
  # sysdep-rtld-routines
endif
