/* Linx syscall numbers (bring-up).

   glibc normally uses an autogenerated arch-syscall.h list rather than
   <asm/unistd.h>. During the Linx bring-up we include the installed kernel
   UAPI header to provide __NR_* definitions.  */

#include <asm/unistd.h>

